package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CITAS".
 */
@Entity
public class Citas {
    private Long codigoCita;
    private java.util.Date fechaCita;

    @Generated
    public Citas() {
    }

    @Generated
    public Citas(Long codigoCita, java.util.Date fechaCita) {
        this.codigoCita = codigoCita;
        this.fechaCita = fechaCita;
    }

    public Long getCodigoCita() {
        return codigoCita;
    }

    public void setCodigoCita(Long codigoCita) {
        this.codigoCita = codigoCita;
    }

    public java.util.Date getFechaCita() {
        return fechaCita;
    }

    public void setFechaCita(java.util.Date fechaCita) {
        this.fechaCita = fechaCita;
    }

}
