package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CLINICAS".
 */
@Entity
public class Clinicas {

    @Id
    private Integer codigoClinica;
    private String NombreClinica;

    @Generated
    public Clinicas() {
    }

    public Clinicas(Integer codigoClinica) {
        this.codigoClinica = codigoClinica;
    }

    @Generated
    public Clinicas(Integer codigoClinica, String NombreClinica) {
        this.codigoClinica = codigoClinica;
        this.NombreClinica = NombreClinica;
    }

    public Integer getCodigoClinica() {
        return codigoClinica;
    }

    public void setCodigoClinica(Integer codigoClinica) {
        this.codigoClinica = codigoClinica;
    }

    public String getNombreClinica() {
        return NombreClinica;
    }

    public void setNombreClinica(String NombreClinica) {
        this.NombreClinica = NombreClinica;
    }

}
