package com.palominocia.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.palominocia.dao.Clinicas;
import com.palominocia.dao.Sedes;
import com.palominocia.dao.Medicos;
import com.palominocia.dao.Especialidad;
import com.palominocia.dao.Citas;
import com.palominocia.dao.Diagnostico;
import com.palominocia.dao.Receta;
import com.palominocia.dao.Medicinas;

import com.palominocia.dao.ClinicasDao;
import com.palominocia.dao.SedesDao;
import com.palominocia.dao.MedicosDao;
import com.palominocia.dao.EspecialidadDao;
import com.palominocia.dao.CitasDao;
import com.palominocia.dao.DiagnosticoDao;
import com.palominocia.dao.RecetaDao;
import com.palominocia.dao.MedicinasDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clinicasDaoConfig;
    private final DaoConfig sedesDaoConfig;
    private final DaoConfig medicosDaoConfig;
    private final DaoConfig especialidadDaoConfig;
    private final DaoConfig citasDaoConfig;
    private final DaoConfig diagnosticoDaoConfig;
    private final DaoConfig recetaDaoConfig;
    private final DaoConfig medicinasDaoConfig;

    private final ClinicasDao clinicasDao;
    private final SedesDao sedesDao;
    private final MedicosDao medicosDao;
    private final EspecialidadDao especialidadDao;
    private final CitasDao citasDao;
    private final DiagnosticoDao diagnosticoDao;
    private final RecetaDao recetaDao;
    private final MedicinasDao medicinasDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clinicasDaoConfig = daoConfigMap.get(ClinicasDao.class).clone();
        clinicasDaoConfig.initIdentityScope(type);

        sedesDaoConfig = daoConfigMap.get(SedesDao.class).clone();
        sedesDaoConfig.initIdentityScope(type);

        medicosDaoConfig = daoConfigMap.get(MedicosDao.class).clone();
        medicosDaoConfig.initIdentityScope(type);

        especialidadDaoConfig = daoConfigMap.get(EspecialidadDao.class).clone();
        especialidadDaoConfig.initIdentityScope(type);

        citasDaoConfig = daoConfigMap.get(CitasDao.class).clone();
        citasDaoConfig.initIdentityScope(type);

        diagnosticoDaoConfig = daoConfigMap.get(DiagnosticoDao.class).clone();
        diagnosticoDaoConfig.initIdentityScope(type);

        recetaDaoConfig = daoConfigMap.get(RecetaDao.class).clone();
        recetaDaoConfig.initIdentityScope(type);

        medicinasDaoConfig = daoConfigMap.get(MedicinasDao.class).clone();
        medicinasDaoConfig.initIdentityScope(type);

        clinicasDao = new ClinicasDao(clinicasDaoConfig, this);
        sedesDao = new SedesDao(sedesDaoConfig, this);
        medicosDao = new MedicosDao(medicosDaoConfig, this);
        especialidadDao = new EspecialidadDao(especialidadDaoConfig, this);
        citasDao = new CitasDao(citasDaoConfig, this);
        diagnosticoDao = new DiagnosticoDao(diagnosticoDaoConfig, this);
        recetaDao = new RecetaDao(recetaDaoConfig, this);
        medicinasDao = new MedicinasDao(medicinasDaoConfig, this);

        registerDao(Clinicas.class, clinicasDao);
        registerDao(Sedes.class, sedesDao);
        registerDao(Medicos.class, medicosDao);
        registerDao(Especialidad.class, especialidadDao);
        registerDao(Citas.class, citasDao);
        registerDao(Diagnostico.class, diagnosticoDao);
        registerDao(Receta.class, recetaDao);
        registerDao(Medicinas.class, medicinasDao);
    }
    
    public void clear() {
        clinicasDaoConfig.clearIdentityScope();
        sedesDaoConfig.clearIdentityScope();
        medicosDaoConfig.clearIdentityScope();
        especialidadDaoConfig.clearIdentityScope();
        citasDaoConfig.clearIdentityScope();
        diagnosticoDaoConfig.clearIdentityScope();
        recetaDaoConfig.clearIdentityScope();
        medicinasDaoConfig.clearIdentityScope();
    }

    public ClinicasDao getClinicasDao() {
        return clinicasDao;
    }

    public SedesDao getSedesDao() {
        return sedesDao;
    }

    public MedicosDao getMedicosDao() {
        return medicosDao;
    }

    public EspecialidadDao getEspecialidadDao() {
        return especialidadDao;
    }

    public CitasDao getCitasDao() {
        return citasDao;
    }

    public DiagnosticoDao getDiagnosticoDao() {
        return diagnosticoDao;
    }

    public RecetaDao getRecetaDao() {
        return recetaDao;
    }

    public MedicinasDao getMedicinasDao() {
        return medicinasDao;
    }

}
