package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DIAGNOSTICO".
 */
@Entity
public class Diagnostico {
    private Long codigoDiagnostico;
    private String indicaciones;
    private java.util.Date fechaDiagnostico;

    @Generated
    public Diagnostico() {
    }

    @Generated
    public Diagnostico(Long codigoDiagnostico, String indicaciones, java.util.Date fechaDiagnostico) {
        this.codigoDiagnostico = codigoDiagnostico;
        this.indicaciones = indicaciones;
        this.fechaDiagnostico = fechaDiagnostico;
    }

    public Long getCodigoDiagnostico() {
        return codigoDiagnostico;
    }

    public void setCodigoDiagnostico(Long codigoDiagnostico) {
        this.codigoDiagnostico = codigoDiagnostico;
    }

    public String getIndicaciones() {
        return indicaciones;
    }

    public void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }

    public java.util.Date getFechaDiagnostico() {
        return fechaDiagnostico;
    }

    public void setFechaDiagnostico(java.util.Date fechaDiagnostico) {
        this.fechaDiagnostico = fechaDiagnostico;
    }

}
