package com.palominocia.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIAGNOSTICO".
*/
public class DiagnosticoDao extends AbstractDao<Diagnostico, Void> {

    public static final String TABLENAME = "DIAGNOSTICO";

    /**
     * Properties of entity Diagnostico.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
    }


    public DiagnosticoDao(DaoConfig config) {
        super(config);
    }
    
    public DiagnosticoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIAGNOSTICO\" (" + //
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIAGNOSTICO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Diagnostico entity) {
        stmt.clearBindings();
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Diagnostico entity) {
        stmt.clearBindings();
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Diagnostico readEntity(Cursor cursor, int offset) {
        Diagnostico entity = new Diagnostico( //
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Diagnostico entity, int offset) {
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Diagnostico entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Diagnostico entity) {
        return null;
    }

    @Override
    public boolean hasKey(Diagnostico entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
