package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEDICO_ESPECIALIDAD".
 */
@Entity
public class MedicoEspecialidad {
    private String mcaEspecialidadActiva;

    @Generated
    public MedicoEspecialidad() {
    }

    @Generated
    public MedicoEspecialidad(String mcaEspecialidadActiva) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
    }

    public String getMcaEspecialidadActiva() {
        return mcaEspecialidadActiva;
    }

    public void setMcaEspecialidadActiva(String mcaEspecialidadActiva) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
    }

}
