package com.palominocia.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICOS".
*/
public class MedicosDao extends AbstractDao<Medicos, Void> {

    public static final String TABLENAME = "MEDICOS";

    /**
     * Properties of entity Medicos.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
    }


    public MedicosDao(DaoConfig config) {
        super(config);
    }
    
    public MedicosDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICOS\" (" + //
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICOS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Medicos entity) {
        stmt.clearBindings();
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Medicos entity) {
        stmt.clearBindings();
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Medicos readEntity(Cursor cursor, int offset) {
        Medicos entity = new Medicos( //
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Medicos entity, int offset) {
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Medicos entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Medicos entity) {
        return null;
    }

    @Override
    public boolean hasKey(Medicos entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
