package com.palominocia.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICINAS".
*/
public class MedicinasDao extends AbstractDao<Medicinas, Long> {

    public static final String TABLENAME = "MEDICINAS";

    /**
     * Properties of entity Medicinas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CodigoMedicina = new Property(0, long.class, "codigoMedicina", true, "CODIGO_MEDICINA");
        public final static Property NombreMedicina = new Property(1, String.class, "nombreMedicina", false, "NOMBRE_MEDICINA");
        public final static Property PresentacionMedicina = new Property(2, String.class, "presentacionMedicina", false, "PRESENTACION_MEDICINA");
    }


    public MedicinasDao(DaoConfig config) {
        super(config);
    }
    
    public MedicinasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICINAS\" (" + //
                "\"CODIGO_MEDICINA\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: codigoMedicina
                "\"NOMBRE_MEDICINA\" TEXT," + // 1: nombreMedicina
                "\"PRESENTACION_MEDICINA\" TEXT);"); // 2: presentacionMedicina
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICINAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Medicinas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodigoMedicina());
 
        String nombreMedicina = entity.getNombreMedicina();
        if (nombreMedicina != null) {
            stmt.bindString(2, nombreMedicina);
        }
 
        String presentacionMedicina = entity.getPresentacionMedicina();
        if (presentacionMedicina != null) {
            stmt.bindString(3, presentacionMedicina);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Medicinas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodigoMedicina());
 
        String nombreMedicina = entity.getNombreMedicina();
        if (nombreMedicina != null) {
            stmt.bindString(2, nombreMedicina);
        }
 
        String presentacionMedicina = entity.getPresentacionMedicina();
        if (presentacionMedicina != null) {
            stmt.bindString(3, presentacionMedicina);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Medicinas readEntity(Cursor cursor, int offset) {
        Medicinas entity = new Medicinas( //
            cursor.getLong(offset + 0), // codigoMedicina
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombreMedicina
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // presentacionMedicina
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Medicinas entity, int offset) {
        entity.setCodigoMedicina(cursor.getLong(offset + 0));
        entity.setNombreMedicina(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPresentacionMedicina(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Medicinas entity, long rowId) {
        entity.setCodigoMedicina(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Medicinas entity) {
        if(entity != null) {
            return entity.getCodigoMedicina();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Medicinas entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
