package com.palominocia.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICINAS".
*/
public class MedicinasDao extends AbstractDao<Medicinas, Void> {

    public static final String TABLENAME = "MEDICINAS";

    /**
     * Properties of entity Medicinas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
    }


    public MedicinasDao(DaoConfig config) {
        super(config);
    }
    
    public MedicinasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICINAS\" (" + //
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICINAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Medicinas entity) {
        stmt.clearBindings();
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Medicinas entity) {
        stmt.clearBindings();
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Medicinas readEntity(Cursor cursor, int offset) {
        Medicinas entity = new Medicinas( //
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Medicinas entity, int offset) {
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Medicinas entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Medicinas entity) {
        return null;
    }

    @Override
    public boolean hasKey(Medicinas entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
