package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RECETA".
 */
@Entity
public class Receta {

    @Generated
    public Receta() {
    }

    @Generated
    public Receta() {
    }

}
