package com.palominocia.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEDES".
*/
public class SedesDao extends AbstractDao<Sedes, Integer> {

    public static final String TABLENAME = "SEDES";

    /**
     * Properties of entity Sedes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CodigoSede = new Property(0, Integer.class, "codigoSede", true, "CODIGO_SEDE");
        public final static Property NombreSede = new Property(1, String.class, "NombreSede", false, "NOMBRE_SEDE");
    }


    public SedesDao(DaoConfig config) {
        super(config);
    }
    
    public SedesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEDES\" (" + //
                "\"CODIGO_SEDE\" INTEGER PRIMARY KEY ," + // 0: codigoSede
                "\"NOMBRE_SEDE\" TEXT);"); // 1: NombreSede
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEDES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Sedes entity) {
        stmt.clearBindings();
 
        Integer codigoSede = entity.getCodigoSede();
        if (codigoSede != null) {
            stmt.bindLong(1, codigoSede);
        }
 
        String NombreSede = entity.getNombreSede();
        if (NombreSede != null) {
            stmt.bindString(2, NombreSede);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Sedes entity) {
        stmt.clearBindings();
 
        Integer codigoSede = entity.getCodigoSede();
        if (codigoSede != null) {
            stmt.bindLong(1, codigoSede);
        }
 
        String NombreSede = entity.getNombreSede();
        if (NombreSede != null) {
            stmt.bindString(2, NombreSede);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0);
    }    

    @Override
    public Sedes readEntity(Cursor cursor, int offset) {
        Sedes entity = new Sedes( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // codigoSede
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // NombreSede
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Sedes entity, int offset) {
        entity.setCodigoSede(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setNombreSede(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(Sedes entity, long rowId) {
        return entity.getCodigoSede();
    }
    
    @Override
    public Integer getKey(Sedes entity) {
        if(entity != null) {
            return entity.getCodigoSede();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Sedes entity) {
        return entity.getCodigoSede() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
