package com.palominocia.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SEDES".
 */
@Entity
public class Sedes {

    @Id
    private Integer codigoSede;
    private String NombreSede;

    @Generated
    public Sedes() {
    }

    public Sedes(Integer codigoSede) {
        this.codigoSede = codigoSede;
    }

    @Generated
    public Sedes(Integer codigoSede, String NombreSede) {
        this.codigoSede = codigoSede;
        this.NombreSede = NombreSede;
    }

    public Integer getCodigoSede() {
        return codigoSede;
    }

    public void setCodigoSede(Integer codigoSede) {
        this.codigoSede = codigoSede;
    }

    public String getNombreSede() {
        return NombreSede;
    }

    public void setNombreSede(String NombreSede) {
        this.NombreSede = NombreSede;
    }

}
