package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CLINICAS".
 */
@Entity
public class Clinicas {

    @Id(autoincrement = true)
    private long codigoClinica;
    private String NombreClinica;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 719400009)
    public Clinicas() {
    }

    public Clinicas(long codigoClinica) {
        this.codigoClinica = codigoClinica;
    }

    @Generated(hash = 657062358)
    public Clinicas(long codigoClinica, String NombreClinica) {
        this.codigoClinica = codigoClinica;
        this.NombreClinica = NombreClinica;
    }

    public long getCodigoClinica() {
        return codigoClinica;
    }

    public void setCodigoClinica(long codigoClinica) {
        this.codigoClinica = codigoClinica;
    }

    public String getNombreClinica() {
        return NombreClinica;
    }

    public void setNombreClinica(String NombreClinica) {
        this.NombreClinica = NombreClinica;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
