package com.palominocia.medicalhistory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ESPECIALIDAD".
*/
public class EspecialidadDao extends AbstractDao<Especialidad, Long> {

    public static final String TABLENAME = "ESPECIALIDAD";

    /**
     * Properties of entity Especialidad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CodigoEspecialidad = new Property(0, long.class, "codigoEspecialidad", true, "CODIGO_ESPECIALIDAD");
        public final static Property NombreEspecialidad = new Property(1, String.class, "nombreEspecialidad", false, "NOMBRE_ESPECIALIDAD");
    }


    public EspecialidadDao(DaoConfig config) {
        super(config);
    }
    
    public EspecialidadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ESPECIALIDAD\" (" + //
                "\"CODIGO_ESPECIALIDAD\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: codigoEspecialidad
                "\"NOMBRE_ESPECIALIDAD\" TEXT);"); // 1: nombreEspecialidad
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ESPECIALIDAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Especialidad entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodigoEspecialidad());
 
        String nombreEspecialidad = entity.getNombreEspecialidad();
        if (nombreEspecialidad != null) {
            stmt.bindString(2, nombreEspecialidad);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Especialidad entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodigoEspecialidad());
 
        String nombreEspecialidad = entity.getNombreEspecialidad();
        if (nombreEspecialidad != null) {
            stmt.bindString(2, nombreEspecialidad);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Especialidad readEntity(Cursor cursor, int offset) {
        Especialidad entity = new Especialidad( //
            cursor.getLong(offset + 0), // codigoEspecialidad
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // nombreEspecialidad
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Especialidad entity, int offset) {
        entity.setCodigoEspecialidad(cursor.getLong(offset + 0));
        entity.setNombreEspecialidad(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Especialidad entity, long rowId) {
        entity.setCodigoEspecialidad(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Especialidad entity) {
        if(entity != null) {
            return entity.getCodigoEspecialidad();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Especialidad entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
