package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ESPECIALIDAD".
 */
@Entity
public class Especialidad {

    @Id(autoincrement = true)
    private long codigoEspecialidad;
    private String nombreEspecialidad;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1938652467)
    public Especialidad() {
    }

    public Especialidad(long codigoEspecialidad) {
        this.codigoEspecialidad = codigoEspecialidad;
    }

    @Generated(hash = 1592583499)
    public Especialidad(long codigoEspecialidad, String nombreEspecialidad) {
        this.codigoEspecialidad = codigoEspecialidad;
        this.nombreEspecialidad = nombreEspecialidad;
    }

    public long getCodigoEspecialidad() {
        return codigoEspecialidad;
    }

    public void setCodigoEspecialidad(long codigoEspecialidad) {
        this.codigoEspecialidad = codigoEspecialidad;
    }

    public String getNombreEspecialidad() {
        return nombreEspecialidad;
    }

    public void setNombreEspecialidad(String nombreEspecialidad) {
        this.nombreEspecialidad = nombreEspecialidad;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
