package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.palominocia.medicalhistory.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ESPECIALIDAD".
 */
@Entity(active = true)
public class Especialidad {

    @Id(autoincrement = true)
    private Long id;
    private Long codigoEspecialidad;
    private String nombreEspecialidad;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient EspecialidadDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "codigoEspecialidad")
    })
    private List<MedicoEspecialidad> medicoEspecialidadList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Especialidad() {
    }

    public Especialidad(Long id) {
        this.id = id;
    }

    @Generated
    public Especialidad(Long id, Long codigoEspecialidad, String nombreEspecialidad) {
        this.id = id;
        this.codigoEspecialidad = codigoEspecialidad;
        this.nombreEspecialidad = nombreEspecialidad;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEspecialidadDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCodigoEspecialidad() {
        return codigoEspecialidad;
    }

    public void setCodigoEspecialidad(Long codigoEspecialidad) {
        this.codigoEspecialidad = codigoEspecialidad;
    }

    public String getNombreEspecialidad() {
        return nombreEspecialidad;
    }

    public void setNombreEspecialidad(String nombreEspecialidad) {
        this.nombreEspecialidad = nombreEspecialidad;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<MedicoEspecialidad> getMedicoEspecialidadList() {
        if (medicoEspecialidadList == null) {
            __throwIfDetached();
            MedicoEspecialidadDao targetDao = daoSession.getMedicoEspecialidadDao();
            List<MedicoEspecialidad> medicoEspecialidadListNew = targetDao._queryEspecialidad_MedicoEspecialidadList(id);
            synchronized (this) {
                if(medicoEspecialidadList == null) {
                    medicoEspecialidadList = medicoEspecialidadListNew;
                }
            }
        }
        return medicoEspecialidadList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetMedicoEspecialidadList() {
        medicoEspecialidadList = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
