package com.palominocia.medicalhistory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ESPECIALIDAD".
*/
public class EspecialidadDao extends AbstractDao<Especialidad, Long> {

    public static final String TABLENAME = "ESPECIALIDAD";

    /**
     * Properties of entity Especialidad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CodigoEspecialidad = new Property(1, Long.class, "codigoEspecialidad", false, "CODIGO_ESPECIALIDAD");
        public final static Property NombreEspecialidad = new Property(2, String.class, "nombreEspecialidad", false, "NOMBRE_ESPECIALIDAD");
    }

    private DaoSession daoSession;


    public EspecialidadDao(DaoConfig config) {
        super(config);
    }
    
    public EspecialidadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ESPECIALIDAD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CODIGO_ESPECIALIDAD\" INTEGER," + // 1: codigoEspecialidad
                "\"NOMBRE_ESPECIALIDAD\" TEXT);"); // 2: nombreEspecialidad
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ESPECIALIDAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Especialidad entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long codigoEspecialidad = entity.getCodigoEspecialidad();
        if (codigoEspecialidad != null) {
            stmt.bindLong(2, codigoEspecialidad);
        }
 
        String nombreEspecialidad = entity.getNombreEspecialidad();
        if (nombreEspecialidad != null) {
            stmt.bindString(3, nombreEspecialidad);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Especialidad entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long codigoEspecialidad = entity.getCodigoEspecialidad();
        if (codigoEspecialidad != null) {
            stmt.bindLong(2, codigoEspecialidad);
        }
 
        String nombreEspecialidad = entity.getNombreEspecialidad();
        if (nombreEspecialidad != null) {
            stmt.bindString(3, nombreEspecialidad);
        }
    }

    @Override
    protected final void attachEntity(Especialidad entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Especialidad readEntity(Cursor cursor, int offset) {
        Especialidad entity = new Especialidad( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // codigoEspecialidad
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // nombreEspecialidad
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Especialidad entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigoEspecialidad(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setNombreEspecialidad(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Especialidad entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Especialidad entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Especialidad entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
