package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEDICOS".
 */
@Entity
public class Medicos {

    @Id(autoincrement = true)
    private long codigoMedico;
    private String nombreMedico;
    private String urlMedico;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 59025677)
    public Medicos() {
    }

    public Medicos(long codigoMedico) {
        this.codigoMedico = codigoMedico;
    }

    @Generated(hash = 386622072)
    public Medicos(long codigoMedico, String nombreMedico, String urlMedico) {
        this.codigoMedico = codigoMedico;
        this.nombreMedico = nombreMedico;
        this.urlMedico = urlMedico;
    }

    public long getCodigoMedico() {
        return codigoMedico;
    }

    public void setCodigoMedico(long codigoMedico) {
        this.codigoMedico = codigoMedico;
    }

    public String getNombreMedico() {
        return nombreMedico;
    }

    public void setNombreMedico(String nombreMedico) {
        this.nombreMedico = nombreMedico;
    }

    public String getUrlMedico() {
        return urlMedico;
    }

    public void setUrlMedico(String urlMedico) {
        this.urlMedico = urlMedico;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
