package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEDICINAS".
 */
@Entity
public class Medicinas {

    @Id(autoincrement = true)
    private Long codigoMedicina;
    private String nombreMedicina;
    private String presentacionMedicina;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Medicinas() {
    }

    public Medicinas(Long codigoMedicina) {
        this.codigoMedicina = codigoMedicina;
    }

    @Generated
    public Medicinas(Long codigoMedicina, String nombreMedicina, String presentacionMedicina) {
        this.codigoMedicina = codigoMedicina;
        this.nombreMedicina = nombreMedicina;
        this.presentacionMedicina = presentacionMedicina;
    }

    public Long getCodigoMedicina() {
        return codigoMedicina;
    }

    public void setCodigoMedicina(Long codigoMedicina) {
        this.codigoMedicina = codigoMedicina;
    }

    public String getNombreMedicina() {
        return nombreMedicina;
    }

    public void setNombreMedicina(String nombreMedicina) {
        this.nombreMedicina = nombreMedicina;
    }

    public String getPresentacionMedicina() {
        return presentacionMedicina;
    }

    public void setPresentacionMedicina(String presentacionMedicina) {
        this.presentacionMedicina = presentacionMedicina;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
