package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEDICO_ESPECIALIDAD".
 */
@Entity
public class MedicoEspecialidad {
    private String mcaEspecialidadActiva;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1918189784)
    public MedicoEspecialidad() {
    }

    @Generated(hash = 1022360081)
    public MedicoEspecialidad(String mcaEspecialidadActiva) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
    }

    public String getMcaEspecialidadActiva() {
        return mcaEspecialidadActiva;
    }

    public void setMcaEspecialidadActiva(String mcaEspecialidadActiva) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
