package com.palominocia.medicalhistory.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEDICO_ESPECIALIDAD".
*/
public class MedicoEspecialidadDao extends AbstractDao<MedicoEspecialidad, Void> {

    public static final String TABLENAME = "MEDICO_ESPECIALIDAD";

    /**
     * Properties of entity MedicoEspecialidad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property McaEspecialidadActiva = new Property(0, String.class, "mcaEspecialidadActiva", false, "MCA_ESPECIALIDAD_ACTIVA");
    }


    public MedicoEspecialidadDao(DaoConfig config) {
        super(config);
    }
    
    public MedicoEspecialidadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEDICO_ESPECIALIDAD\" (" + //
                "\"MCA_ESPECIALIDAD_ACTIVA\" TEXT);"); // 0: mcaEspecialidadActiva
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEDICO_ESPECIALIDAD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MedicoEspecialidad entity) {
        stmt.clearBindings();
 
        String mcaEspecialidadActiva = entity.getMcaEspecialidadActiva();
        if (mcaEspecialidadActiva != null) {
            stmt.bindString(1, mcaEspecialidadActiva);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MedicoEspecialidad entity) {
        stmt.clearBindings();
 
        String mcaEspecialidadActiva = entity.getMcaEspecialidadActiva();
        if (mcaEspecialidadActiva != null) {
            stmt.bindString(1, mcaEspecialidadActiva);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MedicoEspecialidad readEntity(Cursor cursor, int offset) {
        MedicoEspecialidad entity = new MedicoEspecialidad( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // mcaEspecialidadActiva
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MedicoEspecialidad entity, int offset) {
        entity.setMcaEspecialidadActiva(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MedicoEspecialidad entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MedicoEspecialidad entity) {
        return null;
    }

    @Override
    public boolean hasKey(MedicoEspecialidad entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
