package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEDICO_ESPECIALIDAD".
 */
@Entity
public class MedicoEspecialidad {
    private String mcaEspecialidadActiva;
    private Long codigoMedico;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MedicoEspecialidad() {
    }

    @Generated
    public MedicoEspecialidad(String mcaEspecialidadActiva, Long codigoMedico) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
        this.codigoMedico = codigoMedico;
    }

    public String getMcaEspecialidadActiva() {
        return mcaEspecialidadActiva;
    }

    public void setMcaEspecialidadActiva(String mcaEspecialidadActiva) {
        this.mcaEspecialidadActiva = mcaEspecialidadActiva;
    }

    public Long getCodigoMedico() {
        return codigoMedico;
    }

    public void setCodigoMedico(Long codigoMedico) {
        this.codigoMedico = codigoMedico;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
