package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PACIENTE".
 */
@Entity
public class Paciente {

    @Id(autoincrement = true)
    private Long codigoPaciente;
    private String nombrePaciente;
    private java.util.Date fecNacimientoPaciente;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Paciente() {
    }

    public Paciente(Long codigoPaciente) {
        this.codigoPaciente = codigoPaciente;
    }

    @Generated
    public Paciente(Long codigoPaciente, String nombrePaciente, java.util.Date fecNacimientoPaciente) {
        this.codigoPaciente = codigoPaciente;
        this.nombrePaciente = nombrePaciente;
        this.fecNacimientoPaciente = fecNacimientoPaciente;
    }

    public Long getCodigoPaciente() {
        return codigoPaciente;
    }

    public void setCodigoPaciente(Long codigoPaciente) {
        this.codigoPaciente = codigoPaciente;
    }

    public String getNombrePaciente() {
        return nombrePaciente;
    }

    public void setNombrePaciente(String nombrePaciente) {
        this.nombrePaciente = nombrePaciente;
    }

    public java.util.Date getFecNacimientoPaciente() {
        return fecNacimientoPaciente;
    }

    public void setFecNacimientoPaciente(java.util.Date fecNacimientoPaciente) {
        this.fecNacimientoPaciente = fecNacimientoPaciente;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
