package com.palominocia.medicalhistory.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RECETA".
 */
@Entity
public class Receta {

    @Id(autoincrement = true)
    private Long codigoReceta;
    private java.util.Date fechaReceta;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Receta() {
    }

    public Receta(Long codigoReceta) {
        this.codigoReceta = codigoReceta;
    }

    @Generated
    public Receta(Long codigoReceta, java.util.Date fechaReceta) {
        this.codigoReceta = codigoReceta;
        this.fechaReceta = fechaReceta;
    }

    public Long getCodigoReceta() {
        return codigoReceta;
    }

    public void setCodigoReceta(Long codigoReceta) {
        this.codigoReceta = codigoReceta;
    }

    public java.util.Date getFechaReceta() {
        return fechaReceta;
    }

    public void setFechaReceta(java.util.Date fechaReceta) {
        this.fechaReceta = fechaReceta;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
